import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import Footer from "@/containers/Footer";
import Navbar from "@/containers/Navbar";
import Container from "@/containers/Container";
import ToastProvider from "@/providers/ToastProvider";
import ModalProviders from "@/providers/ModalProviders";

const font = Urbanist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Prisma Store",
  description: "Generated by create next app",
  icons: {
    icon: "./favicon.ico",
  },
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Navbar />

        <Container>{children}</Container>
        <Footer />
        <ToastProvider />
        <ModalProviders />
      </body>
    </html>
  );
}
